arch: amd64
language: bash
sudo: required
dist: xenial
services:
    - docker

env:
    global:
        - AUTHOR_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty=\"%aE\")"
        - CI_MANAGERS="$TRAVIS_BUILD_DIR/travis-ci/managers"
        - REPO_ROOT="$TRAVIS_BUILD_DIR"

before_install:
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
    - docker --version
install: $CI_MANAGERS/debian.sh SETUP
script: $CI_MANAGERS/debian.sh ${RUN_MODE}
after_script: $CI_MANAGERS/debian.sh CLEANUP

jobs:
    include:
        - stage: Build & test
          name: Debian Testing $(RUN_MODE)
          env:
              - DEBIAN_RELEASE="testing"
              - CONT_NAME="libbpf-debian-$DEBIAN_RELEASE"
              - RUN_MODE=RUN

        - name: Debian Testing (ASan+UBSan) $(arch)
          env:
              - DEBIAN_RELEASE="testing"
              - CONT_NAME="libbpf-debian-$DEBIAN_RELEASE"
              - RUN_MODE=RUN_ASAN

        - name: Debian Testing (clang)
          env:
              - DEBIAN_RELEASE="testing"
              - CONT_NAME="libbpf-debian-$DEBIAN_RELEASE"
              - RUN_MODE=RUN_CLANG

        - name: Debian Testing (clang ASan+UBSan)
          env:
              - DEBIAN_RELEASE="testing"
              - CONT_NAME="libbpf-debian-$DEBIAN_RELEASE"
              - RUN_MODE=RUN_CLANG_ASAN

        - name: Debian Testing (gcc-8)
          env:
              - DEBIAN_RELEASE="testing"
              - CONT_NAME="libbpf-debian-$DEBIAN_RELEASE"
              - RUN_MODE=RUN_GCC8

        - name: Debian Testing (gcc-8 ASan+UBSan)
          env:
              - DEBIAN_RELEASE="testing"
              - CONT_NAME="libbpf-debian-$DEBIAN_RELEASE"
              - RUN_MODE=RUN_GCC8_ASAN

        - name: Ubuntu Xenial
          before_install:
          install: 
          script: sudo $CI_MANAGERS/xenial.sh
          after_script:
